# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: n
  password:
  timeout: 5000

development:
  <<: *default
  database: whoisapi_development

production:
  <<: *default
  database: bulkwhois
  username: bulk
  password: bulk_whois_123
